### PR TITLE
Bugfix/43/scroll to top s2s logo

### LINKED ISSUE #43: [Home page] The “Space2Study” logo button does not return to the home page welcoming block after clicking it.
**Description**: The “Space2Study” logo button does not return to the home page welcoming block after clicking it.

**Environment**: Windows 10 x64, Microsoft Edge 112.0.1722.48, Google Chrome 112.0.5615.122, MacOS Big Sur 11.7.3 Safari 16.3 (16614.4.6.11.6, 16614)

**Reproducible**: always.

**Preconditions:**
The site is opened.
The user is not logged in.

**Steps to reproduce:**
1. Scroll down to the “How it works” block on the home page.
2. Click on the “Space2Study” logo button on the header.
3. Take a look at the home page.

**Actual result:**
The “Space2Study” logo button does **NOT** return to the home page welcoming block after clicking it.
**Expected result:**
The system scrolls back to the home page welcoming block after clicking on the “Space2Study” logo button on the header.

### PR DESCRIPTION
**Pull request by lublubczyk**
did scrolling to the top of the home page

### CODE REVIEW

**Review by zim89 — APPROVED** [review]

**Review by lsofiabo — APPROVED** [review]

**Review by VoitV — APPROVED** [review]

**Review by AntonRomanov999 — APPROVED** [review]

File: src/containers/layout/navbar/NavBar.tsx [hunk 1]
```diff
@@ -99,10 +97,16 @@ const Navbar = () => {
     )
   })
 
+  const scrollToWelcome = (): void => {
+    const welcome = document.getElementById(guestRoutes.welcome.route)
+    if (welcome) welcome.scrollIntoView({ behavior: 'smooth' })
+  }
+
```
Comment (vlad-khrychov) [inline src/containers/layout/navbar/NavBar.tsx]: In React we try do not use `getElementById`. Look at `findOffersMenu` (59th row) items have scroll behavior.

**Review by vlad-khrychov — CHANGES_REQUESTED** [review]

**Review by nadraharr — APPROVED** [review]

**Review by zim89 — APPROVED** [review]

**Review by lsofiabo — APPROVED** [review]

**Review by vlad-khrychov — APPROVED** [review]
